Cannot configure Pipelines at install
The TektonConfig created by the Subscription cannot be updated by Helm.

Error: INSTALLATION FAILED: rendered manifests contain a resource that
already exists. Unable to continue with install: TektonConfig "config"
in namespace "" exists and cannot be imported into the current release:
invalid ownership metadata; label validation error: missing key
"app.kubernetes.io/managed-by": must be set to "Helm"; annotation
validation error: missing key "meta.helm.sh/release-name": must be set
to "my-helm-app01"; annotation validation error: missing key
"meta.helm.sh/release-namespace": must be set to "default"